name: Stockbit Snapshot

on:
  workflow_dispatch:   # bisa dijalankan manual
  schedule:
    - cron: "0 2 * * 1-5"   # tiap hari kerja jam 09:00 WIB (02:00 UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          STOCKBIT_EMAIL: ${{ secrets.STOCKBIT_EMAIL }}
          STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python main.py
