name: Stockbit Loop (Short)

on:
  workflow_dispatch:

jobs:
  loop:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      STOCKBIT_EMAIL: ${{ secrets.STOCKBIT_EMAIL }}
      STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      STOCKBIT_TOKEN_PATH: token.json

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps + Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

         
  - name: Run loop ~20 menit
        run: |
          python -m live_loop.py

