name: Stockbit Snapshot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1-5"   # 02:00 UTC = 09:00 WIB

jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      STOCKBIT_EMAIL: ${{ secrets.STOCKBIT_EMAIL }}
      STOCKBIT_PASSWORD: ${{ secrets.STOCKBIT_PASSWORD }}
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      STOCKBIT_TOKEN_PATH: token.json

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps + Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run snapshot once
        run: |
          python snap_once.py
